# Default values for jenkins-jobmon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jenkins-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 9118

config:
  jenkinsServer: ""
  secretName: "jenkins-jobmon-secrets"

serviceMonitor:
  enabled: true
  interval: "1m"
  release: "prom-op"
  prometheus: "kube-prometheus"
  port: "metrics"
