apiVersion: v1
kind: Service
metadata:
  name: {{ include "grofers-deployment.fullname" . }}
  labels:
{{ include "grofers-deployment.labels" . | indent 4 }}
{{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "grofers-deployment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
